apiVersion: v1
kind: Service
metadata:
  labels:
    app: e-commerce-mongodb
  name: e-commerce-mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: e-commerce-mongodb