export const FETCH_SHOES_START = 'FETCH_SHOES_START'
export const FETCH_SHOES_SUCCESS = 'FETCH_SHOES_SUCCESS'
export const FETCH_SHOES_FAILED = 'FETCH_SHOES_FAILED'

export const FETCH_PARTICULAR_SHOE_START = 'FETCH_PARTICULAR_SHOE_START'
export const FETCH_PARTICULAR_SHOE_SUCCESS = 'FETCH_PARTICULAR_SHOE_SUCCESS'
export const FETCH_PARTICULAR_SHOE_FAILED = 'FETCH_PARTICULAR_SHOE_FAILED'

export const ON_ADD_BAG_START = 'ON_ADD_BAG_START'
export const ON_ADD_BAG_SUCCESS = 'ON_ADD_BAG_SUCCESS'
export const ON_ADD_BAG_FAILED = 'ON_ADD_BAG_FAILED'
export const ON_FETCH_BAG_START = 'ON_FETCH_BAG_START'
export const ON_FETCH_BAG_SUCCESS = 'ON_FETCH_BAG_SUCCESS'
export const ON_FETCH_BAG_FAILED = 'ON_FETCH_BAG_FAILED'
export const REMOVE_BAG_START = 'REMOVE_BAG_START'
export const REMOVE_BAG_SUCCESS = 'REMOVE_BAG_SUCCESS'
export const REMOVE_BAG_FAILED = 'REMOVE_BAG_FAILED'
export const CLEAR_BAG_START = 'CLEAR_BAG_START'
export const CLEAR_BAG_SUCCESS = 'CLEAR_BAG_SUCCESS'
export const CLEAR_BAG_FAILED = 'CLEAR_BAG_FAILED'

export const ON_ADD_WISHLIST_START = 'ON_ADD_WISHLIST_START'
export const ON_ADD_WISHLIST_SUCCESS = 'ON_ADD_WISHLIST_SUCCESS'
export const ON_ADD_WISHLIST_FAILED = 'ON_ADD_WISHLIST_FAILED'
export const ON_FETCH_WISHLIST_START = 'ON_FETCH_WISHLIST_START'
export const ON_FETCH_WISHLIST_SUCCESS = 'ON_FETCH_WISHLIST_SUCCESS'
export const ON_FETCH_WISHLIST_FAILED = 'ON_FETCH_WISHLIST_FAILED'
export const REMOVE_WISHLIST_START = 'REMOVE_WISHLIST_START'
export const REMOVE_WISHLIST_SUCCESS = 'REMOVE_WISHLIST_SUCCESS'
export const REMOVE_WISHLIST_FAILED = 'REMOVE_WISHLIST_FAILED'

export const ADD_ORDERS_START = 'ADD_ORDERS_START'
export const ADD_ORDERS_SUCCESS = 'ADD_ORDERS_SUCCESS'
export const ADD_ORDERS_FAILED = 'ADD_ORDERS_FAILED'
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED'
export const ORDER_PLACED_ALERT = 'ORDER_PLACED_ALERT'

export const DELETE_TASK_ALERT = 'DELETE_TASK_ALERT'
export const ADD_WISHLIST_ALERT = 'ADD_WISHLIST_ALERT'













// export const DELETE_TASK_START = 'DELETE_TASK_START'
// export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
// export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED'
// export const DELETE_TASK_ALERT = 'DELETE_TASK_ALERT'

// export const EDIT_TASK_INIT = 'EDIT_TASK_INIT'
// export const EDIT_TASK_START = 'EDIT_TASK_START'
// export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS'
// export const EDIT_TASK_FAILED = 'EDIT_TASK_FAILED'

// export const COMPLETED_TASK_START = 'COMPLETED_TASK_START'
// export const COMPLETED_TASK_SUCCESS = 'COMPLETED_TASK_SUCCESS'
// export const COMPLETED_TASK_FAILED = 'COMPLETED_TASK_FAILED'

// export const SEARCH_TASK_SUCCESS = 'SEARCH_TASK_SUCCESS'
// export const SEARCH_TASK_FAILED = 'SEARCH_TASK_FAILED'

// export const MODAL_SHOW = 'MODAL_SHOW'
// export const MODAL_CLOSE = 'MODAL_CLOSE'

// export const SET_TITLE = 'SET_TITLE'
// export const SET_DESCRIPTION = 'SET_DESCRIPTION'
// export const SET_EDIT_TITLE = 'SET_EDIT_TITLE'
// export const SET_EDIT_DESCRIPTION = 'SET_EDIT_DESCRIPTION'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE'